import type { Metadata } from "next";
import "./globals.css";
import MaterialTailwindProvider from "./MaterialTailwindProvider";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
        cz-shortcut-listen="true"
      >
        <MaterialTailwindProvider>
          <Header />
          {children}
          <Footer />
        </MaterialTailwindProvider>
      </body>
    </html>
  );
}
